BASH = [
    # git
    "git status",
    "git status --short",
    "git diff",
    "git diff --stat HEAD~1",
    "git diff origin/main...HEAD -- src/",
    "git log --oneline -20",
    "git log --format='%h %an %s' -10",
    "git log -p -- src/app/models.py",
    "git show HEAD:src/app/models.py",
    "git add -A && git commit -m 'Fix off-by-one in pager'",
    'git commit -am "Update README with install/usage notes"',
    "git checkout -b feature/login-form",
    "git branch -a",
    "git fetch origin && git rebase origin/main",
    "git stash && git pull --rebase && git stash pop",
    "git blame -L 10,40 src/app/views.py",
    "git grep -n 'TODO' -- '*.py'",
    "git ls-files | head -50",
    "git rev-parse --show-toplevel",
    "git remote -v",
    # listing and reading
    "ls",
    "ls -la",
    "ls -la src/",
    "ls -R tests | head -40",
    "ls ~/notes",
    "pwd",
    "cat README.md",
    "cat src/app/__init__.py",
    "cat ./config/settings.yaml",
    "head -n 50 src/app/views.py",
    "tail -f logs/app.log",
    "tail -n 100 /work/logs/server.log",
    "wc -l src/app/models.py",
    "wc -l /work/data.csv",
    "less docs/index.md",
    "file build/output.bin",
    "stat setup.py",
    "du -sh node_modules",
    "tree -L 2 src",
    "cat -n src/app/main.py | sed -n '20,60p'",
    "sed -n '1,40p' src/app/main.py",
    "nl -ba src/app/utils.py | sed -n '100,140p'",
    # grep and friends with quoted programs
    "grep -rn 'def main' src/",
    'grep -rn "import requests" .',
    "grep -n 'TODO\\|FIXME' src/app/views.py",
    "grep -E '^[a-z_]+ = ' src/app/config.py",
    "grep -c '^$' README.md",
    "grep -rl 'class .*Error' src/",
    "grep -o 'https\\?://[^ ]*' docs/links.md | sort -u",
    "grep -v '^#' requirements.txt",
    "grep -rn --include='*.py' 'subprocess' .",
    "grep -E 'version *= *\"[0-9.]+\"' pyproject.toml",
    "grep -P '\\d{4}-\\d{2}-\\d{2}' data/dates.txt",
    "rg -n 'fn main' src",
    "rg --type py 'async def' src/",
    "rg -g '*.ts' 'useEffect' web/src",
    "sed -i 's/foo/bar/g' src/app/config.py",
    "sed -i 's/[[:space:]]*$//' src/app/views.py",
    "sed -i 's/\\/usr\\/local\\/bin/\\/opt\\/bin/g' scripts/install.sh",
    "sed -n '/^def /p' src/app/utils.py",
    "sed -e 's/^ *//' -e 's/ *$//' data/names.txt",
    "sed 's|http://|https://|g' docs/links.md > docs/links2.md",
    "sed -i.bak 's/DEBUG = True/DEBUG = False/' src/app/settings.py",
    "sed -E 's/([0-9]+)\\/([0-9]+)/\\2-\\1/' data/fractions.txt",
    "sed '/^$/d' notes.txt",
    "awk '{print $1}' data/access.log | sort | uniq -c | sort -rn | head",
    "awk -F, '{sum += $3} END {print sum}' data/sales.csv",
    "awk -F/ '{print $NF}' paths.txt",
    "awk 'NR > 1 && $2 ~ /^[0-9]+$/ {print $2/$3}' data/table.tsv",
    "awk '/ERROR/ {count++} END {print count}' logs/app.log",
    "awk '{ printf \"%s/%s\\n\", $1, $2 }' data/pairs.txt",
    "awk 'length($0) > 120' src/app/views.py",
    "cut -d: -f1 data/users.txt",
    "cut -d, -f2,4 data/sales.csv | sort | uniq",
    "tr -d '\\r' < data/win.txt > data/unix.txt",
    "tr '[:upper:]' '[:lower:]' < words.txt",
    "sort -t, -k2 -n data/sales.csv",
    "jq '.dependencies' package.json",
    "jq -r '.items[] | .name' data/items.json",
    "jq '.scripts.build = \"vite build\"' package.json > package.tmp.json",
    "jq -r '.[] | select(.status == \"failed\") | .id' results.json",
    "jq --arg v 1.2.3 '.version = $v' package.json",
    "printf '%s\\n' one two three",
    "printf '%-20s %s\\n' name value",
    "printf 'a/b/c\\n' | cut -d/ -f2",
    "echo 'hello world'",
    'echo "Build finished"',
    "echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.bashrc",
    "echo $PATH",
    "echo $?",
    "diff -u src/app/old.py src/app/new.py",
    "diff <(sort a.txt) <(sort b.txt)",
    "xxd build/output.bin | head",
    # find with quoted globs
    "find . -name '*.py' | head -20",
    "find . -name '*.pyc' -delete",
    "find . -type f -name '*.log' -mtime +7",
    "find src -name '*.test.ts'",
    "find . -path './node_modules' -prune -o -name '*.js' -print",
    "find . -type d -name '__pycache__' -exec rm -rf {} +",
    "find tests -name 'test_*.py' | xargs wc -l",
    "find /work -maxdepth 2 -name '*.toml'",
    "find . -iname '*readme*'",
    "find . -newer setup.py -name '*.py'",
    # package managers
    "pip install -r requirements.txt",
    "pip install -e '.[dev]'",
    "pip install requests==2.32.3",
    "pip list --outdated",
    "pip show numpy",
    "python -m pip install --upgrade pip",
    "uv sync",
    "uv run pytest -x",
    "uv add httpx",
    "npm install",
    "npm run build",
    "npm test -- --watch=false",
    "npx tsc --noEmit",
    "yarn add -D vitest",
    "pnpm install --frozen-lockfile",
    "cargo build --release",
    "cargo test -- --nocapture",
    "go build ./...",
    "go test ./... -run TestParse",
    "poetry install",
    # tests and tools
    "pytest",
    "pytest -q",
    "pytest tests/test_api.py -k 'login and not slow' -v",
    "pytest tests/test_models.py::test_save -x",
    "python -m pytest --maxfail=1 tests/",
    "pytest --cov=src --cov-report=term-missing",
    "ruff check src tests",
    "ruff format .",
    "mypy src",
    "black --check .",
    "eslint 'src/**/*.ts'",
    "prettier --write 'src/**/*.{ts,tsx}'",
    "make",
    "make test",
    "make -j4 build",
    "cmake -S . -B build && cmake --build build",
    "tox -e py312",
    # running scripts
    "python main.py",
    "python scripts/train.py --epochs 3 --lr 0.001",
    "python -c 'import sys; print(sys.version)'",
    'python -c "import numpy; print(numpy.__version__)"',
    "python3 -m http.server 8000",
    "node scripts/build.js",
    "bash scripts/setup.sh",
    "./run.sh --verbose",
    "chmod +x scripts/deploy.sh",
    "time python bench.py",
    "timeout 60 python long_task.py",
    "python report.py && cat out/a.txt",
    # file operations
    "mkdir -p build/output",
    "mkdir -p ~/projects/demo",
    "touch src/app/__init__.py",
    "cp config/example.env config/local.env",
    "cp -r templates/ build/templates/",
    "mv src/app/old_name.py src/app/new_name.py",
    "rm -rf build/ dist/",
    "rm -f /work/tmp/cache.db",
    "ln -s ../shared/config.yaml config.yaml",
    "tar -czf backup.tar.gz src/ tests/",
    "tar -xzf data/archive.tar.gz -C data/",
    "unzip -o data/dataset.zip -d data/raw",
    "zip -r site.zip public/",
    "wc -l /work/data.csv > /work/count.txt",
    "sort -u data/ids.txt > data/ids.sorted.txt",
    "head -c 1000 /dev/urandom | sha256sum",
    "cat /dev/null > logs/app.log",
    # cd and compound
    "cd src && ls",
    "cd /work && make test",
    "cd frontend && npm install && npm run build",
    "cd build && cmake .. && make",
    "cd tests && pytest -q test_api.py",
    "cd docs && make html",
    "cd /work/api && python -m pytest tests/unit",
    "cd .. && ls",
    "pushd src && ls && popd",
    "(cd web && npm ci)",
    # heredocs
    "cat > hello.py <<'EOF'\nprint('hello')\nEOF",
    'cat > config/app.json <<\'EOF\'\n{"name": "demo", "out": "build/out"}\nEOF',
    "cat <<'EOF' > src/app/util.py\ndef join(a, b):\n    return f\"{a}/{b}\"\nEOF",
    "cat > notes.md <<EOF\n# Notes\nSee docs/index.md for details.\nEOF",
    "python - <<'EOF'\nimport json\nprint(json.load(open('package.json'))['name'])\nEOF",
    "cat > .gitignore <<'EOF'\n__pycache__/\n*.pyc\nbuild/\ndist/\nEOF",
    "cat > run.sh <<'EOF'\n#!/bin/sh\nset -e\npython main.py \"$@\"\nEOF",
    "tee requirements.txt <<'EOF'\nrequests\nnumpy\nEOF",
    # network and misc
    "curl -s https://api.github.com/repos/python/cpython | jq '.stargazers_count'",
    "curl -fsSL https://example.com/install.sh -o /work/install.sh",
    "wget https://example.com/data/file.csv -O data/file.csv",
    "ps aux | grep python",
    "kill %1",
    "env | sort",
    "which python",
    "uname -a",
    "df -h",
    "date +%Y-%m-%d",
    "export DEBUG=1 && python main.py",
    "export PATH=$HOME/.local/bin:$PATH",
    "source .venv/bin/activate && pytest",
    "docker build -t app:latest .",
    "docker compose up -d",
    "docker run --rm -v $(pwd):/app app:latest pytest",
    'for f in data/*.csv; do wc -l "$f"; done',
    "for i in 1 2 3; do echo $i; done",
    "if [ -f setup.py ]; then pip install -e .; fi",
    "test -d build || mkdir build",
    "sleep 5",
    "history | tail",
    "wc -l src/*.py",
    "ls *.md",
    "cat ~/.gitconfig",
    "cat $HOME/notes.txt",
    'cat "$HOME/notes.txt"',
    "ls ${HOME}/projects",
    "mkdir -p $HOME/.cache/app",
]

PYTHON = [
    "print('hello')",
    "import os\nprint(os.getcwd())",
    "open('data.csv').read()",
    "with open('data/input.txt') as f:\n    lines = f.readlines()\nprint(len(lines))",
    "with open('out/result.json', 'w') as f:\n    json.dump(result, f)",
    "import pandas as pd\ndf = pd.read_csv('data/sales.csv')\nprint(df.head())",
    "df.to_csv('out/summary.csv', index=False)",
    "from pathlib import Path\nprint(Path('src').glob('*.py'))",
    "from pathlib import Path\nfor p in Path('src').rglob('*.py'):\n    print(p)",
    "Path('build/output').mkdir(parents=True, exist_ok=True)",
    "p = Path('data') / 'raw' / 'file.csv'\nprint(p.exists())",
    "root = Path.cwd()\nprint(root / 'README.md')",
    "text = Path('README.md').read_text()\nprint(text[:200])",
    "Path('notes.txt').write_text('done\\n')",
    "import json\nconfig = json.load(open('config/app.json'))\nprint(config['name'])",
    "import subprocess\nprint(subprocess.run(['git', 'status'], capture_output=True, text=True).stdout)",
    "subprocess.run(['pytest', '-q', 'tests/test_api.py'], check=True)",
    "import glob\nprint(glob.glob('data/*.csv'))",
    "import os\nfor root, dirs, files in os.walk('src'):\n    print(root, len(files))",
    "os.makedirs('out/plots', exist_ok=True)",
    "print(os.listdir('.'))",
    "print(os.path.exists('setup.py'))",
    "path = os.path.join('data', 'raw', 'x.csv')\nprint(path)",
    "name = 'report'\nprint(f'{name}.txt')",
    "print(f'Accuracy: {acc:.2%}')",
    "print(f'{n} of {total} done')",
    "out = f'out/{name}.csv'\ndf.to_csv(out)",
    "for i in range(3):\n    print(f'epoch {i}/{epochs}')",
    "print(f'{a}/{b}')",
    "url = f'https://api.example.com/v1/items/{item_id}'\nprint(url)",
    "x = 10 / 3\nprint(x)",
    "ratio = total / count if count else 0",
    "half = n // 2",
    "print(sum(xs) / len(xs))",
    "import numpy as np\na = np.arange(10)\nprint(a / a.max())",
    "import re\nprint(re.findall(r'\\d+/\\d+', text))",
    "print(re.sub(r'\\s+', ' ', s))",
    "pattern = re.compile(r'^(?P<key>\\w+)\\s*=\\s*(?P<value>.*)$')",
    "date = '2024/01/15'\nprint(date.split('/'))",
    "print('/'.join(['a', 'b', 'c']))",
    "s = 'a' + '/' + 'b'",
    "print('Usage: run.py <input> <output>')",
    "import requests\nr = requests.get('https://httpbin.org/get')\nprint(r.status_code)",
    "import sqlite3\nconn = sqlite3.connect('data/app.db')\nprint(conn.execute('select count(*) from users').fetchone())",
    "import yaml\nprint(yaml.safe_load(open('config/settings.yaml')))",
    "import csv\nwith open('data/sales.csv') as f:\n    rows = list(csv.DictReader(f))\nprint(rows[0])",
    "import matplotlib.pyplot as plt\nplt.plot(xs, ys)\nplt.savefig('out/plot.png')",
    "import pickle\nmodel = pickle.load(open('models/model.pkl', 'rb'))",
    "import shutil\nshutil.copy('config/example.env', 'config/local.env')",
    "shutil.rmtree('build', ignore_errors=True)",
    "import tempfile\nwith tempfile.TemporaryDirectory() as d:\n    print(d)",
    "print(open('/work/data.csv').read()[:100])",
    "with open('/work/out/log.txt', 'a') as f:\n    f.write('ok\\n')",
    "data = {'path': 'src/app', 'count': 3}\nprint(data)",
    "print(sorted(set(words)))",
    "def add(a, b):\n    return a + b\nprint(add(2, 3))",
    "class Point:\n    def __init__(self, x, y):\n        self.x, self.y = x, y",
    "import math\nprint(math.sqrt(2))",
    "print(len(open('README.md').read().splitlines()))",
    "lines = [l.rstrip() for l in open('src/app/views.py')]",
    "print(Path.home())",
    "print(os.environ.get('HOME'))",
    "import sys\nsys.path.insert(0, 'src')\nimport app",
    "from datetime import datetime\nprint(datetime.now().strftime('%Y-%m-%d %H:%M'))",
    "print('%d/%d' % (done, total))",
    "msg = 'saved to ' + out_path\nprint(msg)",
    "print(f'Saved {len(rows)} rows to {path}')",
    "log_path = Path('logs') / f'{run_id}.log'",
    'print(f"{os.getcwd()}/out")',
    "for f in sorted(Path('data').iterdir()):\n    print(f.name)",
]
