services:
  default:
    image: python:3.12.14-slim@sha256:f77ac9e44ae96ef2c90b8053ea08c31f8be030f824196b0ae4db6d462c84e51f
    init: true
    command: tail -f /dev/null
    working_dir: /work
    network_mode: none
    cpus: 1.0
    mem_limit: 512m
